---
vcenter_server:
  description: "The vCenter server to add the ESXi host to"
vcenter_cluster:
  description: "The vCenter Cluster path"
vc_username:
  description: "The username to authenticate with vcenter"
vc_password:
  description: "The password for vc_username"
